16;;1 CD-ROM;;1;;2;;Biochemie - alle Abbildungen des Buches Biochemie;;von Werner Müller-Esterl;;;;;;;;;;470156910;;;;;;2021-04-20 12:30:00;;2021-04-20 12:30:00
14;;Medienkombination;;3;;2;;C für PCs - [für Borland C/C++, Microsoft C/C++, GNU C/C++ und alle anderen ANSI-C-Compiler];;Ulla Kirch-Prinz; Peter Prinz;;;;;;;;;;19335683X;;;;;;2021-04-20 12:30:01;;2021-04-20 12:30:01
4;;1 CD-ROM;;3;;5;;Chirurgie - CD-ROM;;J. Rüdiger Siewert;;;;;;;;;;1158756852;;;;;;2021-04-20 12:30:02;;2021-04-20 12:30:02
16;;1 CD-ROM;;3;;2;;Erste Hilfe bei Gefahrstoff-Notfällen - Gesundheitsgefahren bei Kontakt mit Chemikalien - Giftentfernung - Erste-Hilfe-Maßnahmen - Antidote;;Roth ...;;;;;;;;;;682281743;;;;;;2021-04-20 12:30:05;;2021-04-20 12:30:05
8;;Online-Ressource;;3;;3;;Surgical practice - official journal of the College of Surgeons of Hong Kong;;;;;;;;;;;;48127913X;;;;;;2021-04-20 12:30:06;;2021-04-20 12:30:06
2;;10 CDs, 1 CD (MP3), 1 Beiblatt;;3;;5;;Friede Springer - die Biographie ; 1 Komplettsatz (10 Audio-CDs) + 1 Bonus-CD im MP3-Format;;Kloepfer, Inge;;;;;;;;;;512002746;;;;;;2021-04-20 12:31:34;;2021-04-20 12:31:34
